### ISSUE TITLE
5.0 buildout with "auto-checkout = *" broken

### ISSUE THREAD

**Issue by jensens** [plone/buildout.coredev#101]
because:

First: checkouts of `z3c.formwidget.query` and `Products.ExternalEditor` (svn) are broken
Second::

```
The constraint, 2.13.2, is not consistent with the requirement, 'ExtensionClass>=4.1a1'.
While:
  Installing.
  Getting section instance.
  Initializing section instance.
  Installing recipe plone.recipe.zope2instance.
Error: Bad constraint 2.13.2 ExtensionClass>=4.1a1
```

**Comment by gforcada** [comment]
I spent some time on that since PLOG, but specially the svn thing is really frustrating... my idea was to be able to have **everything** on `src/` so we can run all the tests and thus refactoring can happen.

**Comment by gforcada** [comment]
Seems to be working now on 5.1
