### ISSUE TITLE
Make 5.0 the default branch of coredev

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/buildout.coredev#110]
When you go to https://github.com/plone/buildout.coredev or make a clone, you see branch 4.3 by default. This should become 5.0. I guess it takes someone with admin rights to change this.

**Comment by davisagli** [comment]
Done!

**Comment by davisagli** [comment]
Also added you to the Owners team, Maurits.

**Comment by mauritsvanrees** [comment]
Thanks.

I have made use of my new found powers to protect the 4.3 and 5.0 branches from deletion and from forced pushes. It helps me sleep at night, which I am going to do now. ;-)

**Comment by davisagli** [comment]
Thanks; I didn't realize there was a setting for that. We should do that for the master branch of all our repositories. But not before you sleep. :)

**Comment by mauritsvanrees** [comment]
It is a recent addition to github. See https://github.com/blog/2051-protected-branches-and-required-status-checks

I have now also done this for Products.CMFPlone master and 4.3.x.
