### ISSUE TITLE
trouble setting up the development environment

### ISSUE THREAD

**Issue by reyha** [plone/buildout.coredev#199]
When I run this command ./bin/buildout - v as per the instructions on https://buildoutcoredev.readthedocs.org/en/latest/intro.html, I get this on my console :

reyha@reyha-Lenovo-Z50:~/projects/buidlouts/plone5devel$ ./bin/buildout -v
Installing 'plone.versioncheck', 'mr.developer'.
We have the distribution that satisfies 'plone.versioncheck==1.2.1'.
We have the distribution that satisfies 'mr.developer==1.34'.
Getting required 'requests==2.9.1'
We have the distribution that satisfies 'requests==2.9.1'.
Getting required 'jinja2==2.8'
We have the distribution that satisfies 'jinja2==2.8'.
Getting required 'colorama==0.3.6'
We have the distribution that satisfies 'colorama==0.3.6'.
Getting required 'CacheControl[filecache]==0.11.6'
We have the distribution that satisfies 'CacheControl[filecache]==0.11.6'.
Getting required 'MarkupSafe==0.23'
We have the distribution that satisfies 'MarkupSafe==0.23'.
Getting required 'lockfile==0.12.2'
We have the distribution that satisfies 'lockfile==0.12.2'.
mr.developer: Queued 'Products.CMFPlone' for checkout.
mr.developer: Queued 'Products.PlonePAS' for checkout.
mr.developer: Queued 'mockup' for checkout.
mr.developer: Queued 'plone.app.caching' for checkout.
mr.developer: Queued 'plone.app.contenttypes' for checkout.
mr.developer: Queued 'plone.app.dexterity' for checkout.
mr.developer: Queued 'plone.app.discussion' for checkout.
mr.developer: Queued 'plone.app.event' for checkout.
mr.developer: Queued 'plone.app.intid' for checkout.
mr.developer: Queued 'plone.app.iterate' for checkout.
mr.developer: Queued 'plone.app.layout' for checkout.
mr.developer: Queued 'plone.app.linkintegrity' for checkout.
mr.developer: Queued 'plone.app.locales' for checkout.
mr.developer: Queued 'plone.app.multilingual' for checkout.
mr.developer: Queued 'plone.app.registry' for checkout.
mr.developer: Queued 'plone.app.relationfield' for checkout.
mr.developer: Queued 'plone.app.theming' for checkout.
mr.developer: Queued 'plone.app.upgrade' for checkout.
mr.developer: Queued 'plone.app.vocabularies' for checkout.
mr.developer: Queued 'plone.app.z3cform' for checkout.
mr.developer: Queued 'plone.folder' for checkout.
mr.developer: Queued 'plone.i18n' for checkout.
mr.developer: Queued 'plone.releaser' for checkout.
mr.developer: Queued 'plone.resourceeditor' for checkout.
mr.developer: Queued 'plone.themepreview' for checkout.
mr.developer: Queued 'plonetheme.barceloneta' for checkout.
mr.developer: Updated 'plone.app.caching' with git.
mr.developer: Updated 'Products.PlonePAS' with git.
mr.developer: Updated 'Products.CMFPlone' with git.
mr.developer: Updated 'plone.app.dexterity' with git.
mr.developer: Updated 'plone.app.discussion' with git.
mr.developer: Updated 'mockup' with git.
mr.developer: Updated 'plone.app.contenttypes' with git.
mr.developer: Updated 'plone.app.event' with git.
mr.developer: Updated 'plone.app.intid' with git.
mr.developer: Updated 'plone.app.iterate' with git.
mr.developer: Updated 'plone.app.linkintegrity' with git.
mr.developer: Updated 'plone.app.layout' with git.
mr.developer: Updated 'plone.app.locales' with git.
mr.developer: Updated 'plone.app.relationfield' with git.
mr.developer: Updated 'plone.app.registry' with git.
mr.developer: Updated 'plone.app.multilingual' with git.
mr.developer: Updated 'plone.app.theming' with git.
mr.developer: Updated 'plone.app.vocabularies' with git.
mr.developer: Updated 'plone.app.z3cform' with git.
mr.developer: Updated 'plone.app.upgrade' with git.
mr.developer: Updated 'plone.folder' with git.
mr.developer: Updated 'plone.i18n' with git.
mr.developer: Updated 'plone.resourceeditor' with git.
mr.developer: Updated 'plone.releaser' with git.
mr.developer: Updated 'plone.themepreview' with git.
mr.developer: Updated 'plonetheme.barceloneta' with git.
Installing 'zc.buildout', 'setuptools'.
We have a develop egg: zc.buildout 2.5.0
We have a develop egg: setuptools 20.2.2
Adding find link 'https://pypi.python.org/packages/source/c/certifi/certifi-2015.11.20.tar.gz#md5=25134646672c695c1ff1593c2dd75d08' from setuptools 20.2.2
Adding find link 'https://pypi.python.org/packages/source/w/wincertstore/wincertstore-0.2.zip#md5=ae728f2f007185648d0c7a8679b361e2' from setuptools 20.2.2
Develop: '/home/reyha/projects/buidlouts/plone5devel/src/plone.app.dexterity'
warning: no files found matching '_.txt'
warning: no previously-included files matching '_.pyc' found anywhere in distribution
Develop: '/home/reyha/projects/buidlouts/plone5devel/src/plone.app.linkintegrity'
warning: no previously-included files matching '_.pyc' found anywhere in distribution
Develop: '/home/reyha/projects/buidlouts/plone5devel/src/plone.app.iterate'
warning: no previously-included files matching '_pyc' found anywhere in distribution
Develop: '/home/reyha/projects/buidlouts/plone5devel/src/mockup'
no previously-included directories found matching '.nix'
no previously-included directories found matching 'dist'
no previously-included directories found matching 'mockup/bower_components'
no previously-included directories found matching 'mockup/build'
no previously-included directories found matching 'mockup/coverage'
no previously-included directories found matching 'mockup/docs'
no previously-included directories found matching 'mockup/node_modules'
warning: no previously-included files found matching '.bowerrc'
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching 'Makefile'
warning: no previously-included files found matching '_.sh'
warning: no previously-included files found matching 'Vagrantfile'
warning: no previously-included files matching '_.pyc' found anywhere in distribution
Develop: '/home/reyha/projects/buidlouts/plone5devel/src/plone.app.z3cform'
warning: no previously-included files matching '_pyc' found anywhere in distribution
Develop: '/home/reyha/projects/buidlouts/plone5devel/src/plone.resourceeditor'
warning: no previously-included files matching '_pyc' found anywhere in distribution
Develop: '/home/reyha/projects/buidlouts/plone5devel/src/plone.app.vocabularies'
warning: no files found matching '_' under directory 'docs'
warning: no previously-included files matching '_pyc' found anywhere in distribution
Develop: '/home/reyha/projects/buidlouts/plone5devel/src/plone.releaser'
Develop: '/home/reyha/projects/buidlouts/plone5devel/src/plone.app.upgrade'
warning: no previously-included files matching '_pyc' found anywhere in distribution
Develop: '/home/reyha/projects/buidlouts/plone5devel/src/plone.app.locales'
warning: no files found matching '_.mo' anywhere in distribution
warning: no previously-included files matching '_pyc' found anywhere in distribution
warning: no previously-included files matching '_pyo' found anywhere in distribution
Develop: '/home/reyha/projects/buidlouts/plone5devel/src/Products.PlonePAS'
warning: no previously-included files matching '_.py?' found anywhere in distribution
Develop: '/home/reyha/projects/buidlouts/plone5devel/src/plone.app.intid'
warning: no previously-included files matching '_.pyc' found anywhere in distribution
Develop: '/home/reyha/projects/buidlouts/plone5devel/src/plonetheme.barceloneta'
warning: no previously-included files matching '_.pyc' found anywhere in distribution
no previously-included directories found matching 'design'
Develop: '/home/reyha/projects/buidlouts/plone5devel/src/plone.i18n'
warning: no previously-included files matching '_.pyc' found anywhere in distribution
Develop: '/home/reyha/projects/buidlouts/plone5devel/src/plone.app.registry'
warning: no files found matching '_.txt'
warning: no previously-included files matching '_pyc' found anywhere in distribution
Develop: '/home/reyha/projects/buidlouts/plone5devel/src/Products.CMFPlone'
warning: no previously-included files matching '_.pyc' found anywhere in distribution
Develop: '/home/reyha/projects/buidlouts/plone5devel/src/plone.app.caching'
warning: no previously-included files matching '_pyc' found anywhere in distribution
Develop: '/home/reyha/projects/buidlouts/plone5devel/src/plone.app.relationfield'
warning: no previously-included files matching '_.pyc' found anywhere in distribution
Develop: '/home/reyha/projects/buidlouts/plone5devel/src/plone.app.contenttypes'
warning: no files found matching '_.txt'
warning: no previously-included files matching '_.pyc' found anywhere in distribution
Develop: '/home/reyha/projects/buidlouts/plone5devel/src/plone.app.theming'
warning: no previously-included files matching '_pyc' found anywhere in distribution
Develop: '/home/reyha/projects/buidlouts/plone5devel/src/plone.folder'
warning: no previously-included files matching '_pyc' found anywhere in distribution
Develop: '/home/reyha/projects/buidlouts/plone5devel/src/plone.app.multilingual'
warning: no files found matching '_.txt'
warning: no previously-included files matching '_.pyc' found anywhere in distribution
warning: no previously-included files matching '_.pyo' found anywhere in distribution
warning: no previously-included files matching '.DS_Store' found anywhere in distribution
Develop: '/home/reyha/projects/buidlouts/plone5devel/src/plone.app.discussion'
warning: no files found matching '_.txt'
warning: no previously-included files matching '_.pyc' found anywhere in distribution
Develop: '/home/reyha/projects/buidlouts/plone5devel/src/plone.app.layout'
warning: no previously-included files matching '_.pyc' found anywhere in distribution
Develop: '/home/reyha/projects/buidlouts/plone5devel/src/plone.app.event'
warning: no files found matching '_.mo' anywhere in distribution
warning: no previously-included files matching '_pyc' found anywhere in distribution
warning: no previously-included files matching '_~' found anywhere in distribution
no previously-included directories found matching 'devsrc'
Installing 'zc.recipe.egg'.
We have the distribution that satisfies 'zc.recipe.egg==2.0.3'.
Installing 'collective.xmltestreport'.
We have the distribution that satisfies 'collective.xmltestreport==1.3.3'.
Getting required 'zope.testrunner==4.4.4'
We have the distribution that satisfies 'zope.testrunner==4.4.4'.
Getting required 'zope.testing==3.9.7'
We have the distribution that satisfies 'zope.testing==3.9.7'.
Getting required 'zope.interface==3.6.7'
We have the distribution that satisfies 'zope.interface==3.6.7'.
Getting required 'zope.exceptions==3.6.2'
We have the distribution that satisfies 'zope.exceptions==3.6.2'.
Getting required 'six==1.10.0'
We have the distribution that satisfies 'six==1.10.0'.
Installing 'plone.recipe.zope2instance'.
We have the distribution that satisfies 'plone.recipe.zope2instance==4.2.19'.
Getting required 'ZODB3==3.10.5'
We have the distribution that satisfies 'ZODB3==3.10.5'.
Getting required 'Zope2==2.13.24'
We have the distribution that satisfies 'Zope2==2.13.24'.
Getting required 'mailinglogger==3.8.0'
We have the distribution that satisfies 'mailinglogger==3.8.0'.
Getting required 'zope.event==3.5.2'
We have the distribution that satisfies 'zope.event==3.5.2'.
Getting required 'zdaemon==2.0.7'
We have the distribution that satisfies 'zdaemon==2.0.7'.
Getting required 'ZConfig==2.9.3'
We have the distribution that satisfies 'ZConfig==2.9.3'.
Getting required 'zc.lockfile==1.0.2'
We have the distribution that satisfies 'zc.lockfile==1.0.2'.
Getting required 'transaction==1.1.1'
We have the distribution that satisfies 'transaction==1.1.1'.
Getting required 'Products.StandardCacheManagers==2.13.1'
We have the distribution that satisfies 'Products.StandardCacheManagers==2.13.1'.
Getting required 'Products.PythonScripts==2.13.2'
We have the distribution that satisfies 'Products.PythonScripts==2.13.2'.
Getting required 'Products.MIMETools==2.13.0'
We have the distribution that satisfies 'Products.MIMETools==2.13.0'.
Getting required 'Products.MailHost==2.13.2'
We have the distribution that satisfies 'Products.MailHost==2.13.2'.
Getting required 'Products.ExternalMethod==2.13.1'
We have the distribution that satisfies 'Products.ExternalMethod==2.13.1'.
Getting required 'Products.BTreeFolder2==2.14.0'
We have the distribution that satisfies 'Products.BTreeFolder2==2.14.0'.
Getting required 'zope.viewlet==3.7.2'
We have the distribution that satisfies 'zope.viewlet==3.7.2'.
Getting required 'zope.traversing==3.13.2'
We have the distribution that satisfies 'zope.traversing==3.13.2'.
Getting required 'zope.testbrowser==3.11.1'
We have the distribution that satisfies 'zope.testbrowser==3.11.1'.
Getting required 'zope.tales==3.5.3'
We have the distribution that satisfies 'zope.tales==3.5.3'.
Getting required 'zope.tal==3.5.2'
We have the distribution that satisfies 'zope.tal==3.5.2'.
Getting required 'zope.structuredtext==3.5.1'
We have the distribution that satisfies 'zope.structuredtext==3.5.1'.
Getting required 'zope.size==3.4.1'
We have the distribution that satisfies 'zope.size==3.4.1'.
Getting required 'zope.site==3.9.2'
We have the distribution that satisfies 'zope.site==3.9.2'.
Getting required 'zope.sequencesort==3.4.0'
We have the distribution that satisfies 'zope.sequencesort==3.4.0'.
Getting required 'zope.sendmail==3.7.5'
We have the distribution that satisfies 'zope.sendmail==3.7.5'.
Getting required 'zope.security==3.7.4'
We have the distribution that satisfies 'zope.security==3.7.4'.
Getting required 'zope.schema==4.4.2'
We have the distribution that satisfies 'zope.schema==4.4.2'.
Getting required 'zope.publisher==3.12.6'
We have the distribution that satisfies 'zope.publisher==3.12.6'.
Getting required 'zope.ptresource==3.9.0'
We have the distribution that satisfies 'zope.ptresource==3.9.0'.
Getting required 'zope.proxy==3.6.1'
We have no distributions for zope.proxy that satisfies 'zope.proxy==3.6.1'.
Getting distribution for 'zope.proxy==3.6.1'.
While:
  Installing.
  Getting section instance.
  Initializing section instance.
  Installing recipe plone.recipe.zope2instance.
  Getting distribution for 'zope.proxy==3.6.1'.
Error: Couldn't find a distribution for 'zope.proxy==3.6.1'.

How do I fix this?

**Comment by gforcada** [comment]
Hi @reyha 

maybe that was due to a temporary connection lost, usually re-running `bin/buildout` fixes it. You can as well pass `-vvv` to get **lots** of output that may hint as to what happens more in detail.

**Comment by reyha** [comment]
@gforcada  Hello! Thanks for help.

Like you mentioned, I tried re-running it a lot of times and even passed `-vvv` with `bin/buildout` .Still, it is not working. Here is the link to the output after using `-vvv` : [http://pastie.org/10770913]

**Comment by mauritsvanrees** [comment]
It should get zope.proxy 3.6.1 from here: https://pypi.python.org/simple/zope.proxy/

In your buildout config, do you have a `download-cache` directory?  This option can also be set in `~/.buildout/default.cfg`. If you have set this option, check if the given download-cache directory contains a zope.proxy 3.6.1 and delete it. It may contain a wrong download, for example an html file showing an error instead of the actual zope.proxy distribution. Then try again.

Does installing outside of buildout work, so with a virtualenv?

```
virtualenv foo
cd foo
bin/pip install zope.proxy==3.6.1
```

**Comment by reyha** [comment]
Thanks a lot! Deleting zope.proxy 3.6.1 from the download-cache directory did the job. It got successfully installed. I am now able to follow up the documentation.
