### ISSUE TITLE
Reporting Deadlink

### ISSUE THREAD

**Issue by 1letter** [plone/buildout.coredev#212]
I would only report a little issue. In [documentation.rst](https://github.com/plone/buildout.coredev/blob/5.1/docs/documentation.rst#using-sphinx) is an old linktarget. The first link in the last paragraph with label "Plone Oriented Shpinx Documentation" refers to nirvana.

**Comment by gforcada** [comment]
I updated the link to point to the rst documentation styleguide on docs.plone.org: https://github.com/plone/buildout.coredev/commit/d7afc2dfe2e3b0da7e1e8e333e5baf7b14c6c164

Thanks for reporting!
