### ISSUE TITLE
Update coverage

### ISSUE THREAD

**Issue by idgserpro** [plone/buildout.coredev#235]
Today is used coverage 3.5.2. However, the newer createcoverage requires [coverage>=3.7](https://github.com/reinout/createcoverage/blob/1.5/setup.py#L13). When used createcoverage we get the error:

``` bash
Installing createcoverage.
The constraint, 3.5.2, is not consistent with the requirement, 'coverage>=3.7'.
While:
  Installing createcoverage.
Error: Bad constraint 3.5.2 coverage>=3.7
```

Who pin coverage is [zopetoolkit-1-0-8](https://github.com/zopefoundation/zopetoolkit/blob/1.0.8/ztk-versions.cfg#L105), that is used [here](https://github.com/plone/buildout.coredev/blob/a8c49fb2c794a8ccc4ed1dd7889729de722b5697/versions.cfg#L2). It would not be appropriate to update the zopetoolkit?

**Comment by idgserpro** [comment]
@esteele?

**Comment by mauritsvanrees** [comment]
Seems a good idea to me. I have opened a pull request: https://github.com/plone/buildout.coredev/pull/236

That is for 5.1. Probably good for 5.0 too. For 4.3 I am slightly more hesitant, but.. well, why not.

@hvelarde I think you fixed quite some Travis setup in packages to use the right coverage/createcoverage combination. A newer coverage pin will be easier for new packages. But I wonder if existing packages would then need yet more Travis changes. Do you maybe have a preference for sticking to the old version in coredev 4.3?

I can never remember how I usually fix this in packages: pin an older createcoverage, or pin a newer coverage. I guess I usually pin a newer coverage.

**Comment by mauritsvanrees** [comment]
For now, I have merged to 5.1 and have applied the same change to 5.0.

**Comment by idgserpro** [comment]
@mauritsvanrees I'm +1 to update in Plone 4.3, too. [coveralls](https://github.com/plone/bobtemplates.plone/blob/master/bobtemplates/plone_addon/.travis.yml.bob#L18) only works with coverage>=4.0. See: https://github.com/mozilla/sugardough/issues/94

**Comment by hvelarde** [comment]
@mauritsvanrees I did it manually removing the pinning on coverage; there's no problem on updating on 4.3, this is what I normally do:

```
[versions]
# use latest version of coverage
coverage =
```

not the best thing to do but...

**Comment by mauritsvanrees** [comment]
I have added the pin to 4.3 as well.

So: now coverage is at 3.7.1 in 4.3, 5.0 and 5.1.

Now we might want to update it to a higher version, but I have not tested that.

**Comment by hvelarde** [comment]
I normally use 4.2 without any issues.

**Comment by idgserpro** [comment]
@mauritsvanrees  indeed, the coveralls works with coverage 3.7.1. What happens is that the createcoverage uses the coverage version of buildout and coveralls uses the latest version. These two versions of coverage have to be compatible.

I made [this commit](https://github.com/collective/collective.cover/commit/8c39ee3a27b4293a7ac0e66987f0e95644109340) and it caused [this error](https://travis-ci.org/collective/collective.cover/jobs/154526495#L1488). This is because the version of coverage used by [createcoverage](https://github.com/collective/collective.cover/blob/master/.travis.yml#L43) was 3.7.1, but the version used by [coveralls](https://github.com/collective/collective.cover/blob/master/.travis.yml#L45) was [4.2](https://travis-ci.org/collective/collective.cover/jobs/154526495#L1482).

With [this](https://github.com/collective/collective.cover/commit/6d1652b63ae35b1cca2bb0b8c9f0885d9c22bd6f) other commit worked.

So, we have pin coverage in `.travis.yml`? This may give problem in the future?

@hvelarde opinion?

**Comment by mauritsvanrees** [comment]
Okay, I have pinned coverage 4.2 on the three coredev branches.

**Comment by mauritsvanrees** [comment]
Oops, we use z3c.coverage in coredev 5.0 and 5.1, and this does not work with coverage 4. See https://github.com/zopefoundation/z3c.coverage/issues/2
So Jenkins was broken.
I reverted my commits on all coredev branches, so we are back to version 3.7.1. At least that version is compatible with latest `createcoverage`.

**Comment by gforcada** [comment]
@mauritsvanrees from z3c.coverage readme I see that it is only a tool to create HTML reports out of coverage data (already gathered with another tool), so what's the issue we have with it? We are no generating coverage reports, do we (on jenkins.plone.org I mean)?

**Comment by mauritsvanrees** [comment]
Sigh, we can't really remove z3c.coverage, because z3c.form has it in its `test` dependencies... :-( And apparently it has been there since at least 2007: https://github.com/zopefoundation/z3c.form/commit/87007afb

**Comment by gforcada** [comment]
@mauritsvanrees actually it goes all the way to the first commit! https://github.com/zopefoundation/z3c.form/commit/8cdcafbb35333e61e16e54432571f12528029962

I created a pull request to remove it https://github.com/zopefoundation/z3c.form/pull/49

**Comment by idgserpro** [comment]
In fact, `z3c.form` tests are not run. I didn't see it here: http://jenkins.plone.org/job/plone-5.0-python-2.7/4870/testReport/

**Comment by mauritsvanrees** [comment]
True. We _should_ be running those tests though, I think.  Locally on 5.1 `bin/test -s z3c.form` passes. `z3c.form` should not be in the `excludes` list in `tests.cfg`

But if on the other hand we remove `z3c.form[test]` from the `test-eggs` in `tests.cfg` an added bonus would be that we do not get the `persistent` package in the tests, which is a package that we at least that don't want in a normal instance because it is a newer version of what is already in the ZODB package that we use...

**Comment by idgserpro** [comment]
@mauritsvanrees did you see [this](https://github.com/plone/buildout.coredev/commit/b8b8b1f4f93ec309538298b9171d4bbbbc93d54e)?

@davisagli opinion?

**Comment by mauritsvanrees** [comment]
Seeing that commit, since 2012 we "exclude z3c.form tests, since its tests still depend on too much zope.app.\* stuff."  But that is no longer true for the branches we are using on 4.3, 5.0 and 5.1.

**Comment by idgserpro** [comment]
@mauritsvanrees you can reopen the issue until a new release of z3c.form be released and then update the coverage to the latest version?

**Comment by mauritsvanrees** [comment]
We have new releases of z3c.form that no longer use z3c.coverage. So it should be safe to update to the latest coverage. Let's try.

**Comment by idgserpro** [comment]
@mauritsvanrees can you upgrade on Plone 4.3 as well?

**Comment by mauritsvanrees** [comment]
Ah, yes. On Plone 5.1 it gave no problem, so now we can do this on 4.3 and 5.0 as well. I'll do that directly, without pull request.
Done. Enjoy!

Note that we do still pin z3c.coverage (latest 2.0.3 version) which is incompatible with this newer version of coverage. There is a branch of z3c.coverage which claims compatibility by simply removing the version restriction. That branch is used in the [Zope4 plip config](https://github.com/plone/buildout.coredev/blob/5.1/plip-zope4.cfg#L73).
But as long as we do not use z3c.coverage this is fine. That package seems less needed these days.
