### ISSUE TITLE
Use jenkins to generate plone.versioncheck report everytime a cfg file changes.

### ISSUE THREAD

**Issue by jensens** [plone/buildout.coredev#255]
coming over from #253 (discussion started there) I turn this into an issue:

I sketched my idea of the annotations over here:
https://github.com/plone/plone.versioncheck/issues/25

@gforcada: plone.versioncheck as an extension collecting information about the versions we use in a buildout its just minimal overhead while buildout runs and its already part of buildout.coredev.

To generate the report I'd do a `./bin/versioncheck -prb > dependencies.html`. This shows all versions.

I would let it run everytime when in buildout.coredev one of the main cfg files are changing (but not for PRs, only main branches).  A cfg file mostly changes after PR merges (new checkout), after releases or rare other changes.

Generating the report fires some requests (488 at  the moment) to PyPI in order to get the json with the release-information for each package used. This takes only about 30 seconds on my local machine. Given jenkins has a better internet connectivity it should be faster. I think the html report  can be part of the test result output. I have to admit I have no idea how this in detail need to configured in jenkins.

Would this make sense?

cc @mauritsvanrees

**Comment by mauritsvanrees** [comment]
If hardly anyone ever looks at it, then we don't need to generate this so often. I am not going to look at such output several times per day or week.
Once a week a separate job in the [QA section](http://jenkins.plone.org/view/QA/) could be useful.

**Comment by jensens** [comment]
I added a Github Action for now 
https://github.com/plone/buildout.coredev/actions?query=workflow%3A%22Plone+Versioncheck%22
