### ISSUE TITLE
Get rid of zope.formlib

### ISSUE THREAD

**Issue by gforcada** [plone/buildout.coredev#257]
According to jenkins only these packages depend on zope.formlib (in Plone 5.1):
- [x] https://github.com/plone/plone.portlet.static/issues/13
- [x] https://github.com/plone/plone.app.vocabularies/issues/38
- [x] https://github.com/zopefoundation/Products.GenericSetup/issues/31

On plone.portlet.static there are some references, on comments, to it, which most probably should be clarified as well.

**Comment by gforcada** [comment]
All done!

**Comment by tisto** [comment]
@gforcada Wohoo!
