### ISSUE TITLE
git:// vs. https:// ?

### ISSUE THREAD

**Issue by jensens** [plone/buildout.coredev#263]
in `sources.cfg` remote section https://github.com/plone/buildout.coredev/blob/5.1/sources.cfg#L7-L17 we use for read access the `git://` Urls. 

Why not `https://`? Advantage of `https://` easier to get through firewalls at customer sites.

(I prefer to stick with ssh for write, key-auth is so convenient.)

**Comment by davisagli** [comment]
I'm okay with that as long as we document how to make git automatically switch to ssh for pushes by adding this to ~/.gitconfig:

```
[url "git@github.com:"]
    pushInsteadOf = https://github.com/
    pushInsteadOf = git://github.com/
```

**Comment by gforcada** [comment]
I think one of the reasons to not move it around is that mr.developer would think of the URLs of already cloned repositories to be different and refuse to update...

We can of course improve mr.developer as well :-)

**Comment by thet** [comment]
We already did this switch without documenting...
FWIW, using the tool ``rpl`` I did::

    $ find -path "*.git/config" | xargs rpl git\:\/\/ https\:\/\/
