### ISSUE TITLE
No tests for  Products.PortalTransforms in Jenkins Job for 5.1 python2.7 ????

### ISSUE THREAD

**Issue by fgrcon** [plone/buildout.coredev#314]
Testing https://github.com/plone/Products.CMFPlone/issues/1734  see http://jenkins.plone.org/view/PLIPs/job/plip-1734-icons-and-thumbs I get failures (Products.PortalTransforms is checked out).

**Same results I get locally  for 5.1 coredev (without PLIP!)  - but when I pin Products.PortalTransforms to last Release ( 2.2.3 Feb20) Failures are gone.**

**Comment by gforcada** [comment]
No, they are indeed tested: https://github.com/plone/buildout.coredev/blob/5.1/tests.cfg#L124 and https://github.com/plone/buildout.coredev/blob/5.1/tests.cfg#L250

As you can see on this other PLIP job there are Proucts.PortalTransforms tests results: http://jenkins.plone.org/view/PLIPs/job/plip-collective-indexing/3/testReport/

Or if you look at the at job: http://jenkins.plone.org/job/plone-5.1-python-2.7-at/lastCompletedBuild/testReport/

I would rather say that the two tracebacks on that PLIP are the problem...

**Comment by fgrcon** [comment]
@gforcada : thanks ...

As I dont like Archetypes ;-) i looked at
 http://jenkins.plone.org/job/plone-5.1-python-2.7/lastCompletedBuild/testReport/
and not :
 http://jenkins.plone.org/job/plone-5.1-python-2.7-at/lastCompletedBuild/testReport/

sorry for that, but still a  little bit confusing for test-newbies  :-)

**Comment by gforcada** [comment]
@fgrcon no problem, we need to do a lot of cleanup on our test suite to make it easier to work with and less surprising, blame it to the lack of manpower :-/
