### ISSUE TITLE
The current latest 4.3 release (and 4.3.12) on dist.plone.org point to version 2.0.0 to plone.app.upgrade and break stuff

### ISSUE THREAD

**Issue by do3cc** [plone/buildout.coredev#315]
The README for plone.app.upgrade states that 2.0.0 is for Plone 5.
The pending release 4.3.13 is pointing to 1.4.1 of plone.app.upgrade.
This breaks our builds and forces us to pin 1.4.1 manually

**Comment by gforcada** [comment]
This was fixed on the, now latest 4.3.x release: 4.3.14 already points back to 1.4.1: http://dist.plone.org/release/4-latest/versions.cfg
