### ISSUE TITLE
Can we have a small documentation about how versions.cfg is generated and how to give suggestions? For Plone 4 and Plone 5.

### ISSUE THREAD

**Issue by idgserpro** [plone/buildout.coredev#316]
From https://community.plone.org/t/how-http-dist-plone-org-release-4-3-latest-versions-cfg-is-generated/3357/. We think this would be a nice addition to beginners. Feel free to reject the idea if you think this is bloating the versions file or will give too much false warnings at buildout.coredev.

So, instead of

```cfg
[buildout]
extends = http://dist.plone.org/versions/zopetoolkit-1-0-8-zopeapp-versions.cfg
          http://dist.plone.org/versions/zope-2-13-26-versions.cfg
```

We would have

```cfg
[buildout]
# This file is part of buildout.coredev and it's carefully crafted by the core 
# developers. If you have a suggestion for a package here open an issue at 
# https://github.com/plone/buildout.coredev/issues
extends = http://dist.plone.org/versions/zopetoolkit-1-0-8-zopeapp-versions.cfg
          http://dist.plone.org/versions/zope-2-13-26-versions.cfg
```

As [suggested by @jensens](https://community.plone.org/t/how-http-dist-plone-org-release-4-3-latest-versions-cfg-is-generated/3357/3?u=idgserpro). The explanation

> This file is part of buildout.coredev. It is carefully crafted by the core developers. Any changes are made on a branch, which is tested via our jenkins.plone.org CI before it gets merged. Our Release Manager takes this file, checks it and copies it as part of the release.

Would be a nice addition as well in docs.plone.org.

**Comment by gforcada** [comment]
Sure, that would be ok, would you mind creating a pull request?

**Comment by idgserpro** [comment]
We still can't have a Contributor's Agreement at the company, sorry about the hassle. If we had it we would already be doing a PR here and at docs.plone.org :(

**Comment by tkimnguyen** [comment]
@idgserpro I'm interested to know what the concern is at your company - please email me at undisclosed@xx.yy.zz if you like

**Comment by idgserpro** [comment]
@tkimnguyen noted, you can remove the e-mail now if you want to avoid spam! :laughing:

**Comment by gforcada** [comment]
@idgserpro done on 5.1, 5.0 and 4.3, closing.
