### ISSUE TITLE
plone.formwidget.querystring not used in Plone 5.1?

### ISSUE THREAD

**Issue by gforcada** [plone/buildout.coredev#328]
Is not being used on 4.3 nor 5.1, but is used on 5.0 (master branch). This seems odd... If I remember correctly @sneridagh noticed that as well when upgrading plone.org to the latest 5.1...

**Comment by jensens** [comment]
Except ``plone.app.standardtiles`` uses it. This needs some investigation.

**Comment by fredvd** [comment]
Closing this as 5.0 and 5.1 are already out of maintanance and also out of security support in 8  days.  (https://plone.org/download/release-schedule)
