### ISSUE TITLE
Add pin for plone.api in coredev 4.3?

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/buildout.coredev#358]
I think it makes sense to add a pin for `plone.api` in coredev 4.3. I had created a new package with bobtemplates.plone for Plone 5, but wanted to test it on 4.3 as well, and `plone.api` was the only missing version pin.

Add it to the sources and tests too. It is tested on its own on Travis, and tests pass on 4.3, but testing on Jenkins with the latest stuff seems good.
Well... I wonder about Python 2.6 support. That might be a problem. In that case we can skip the sources and only add the version pin.

Possible downside of pinning: if someone accidentally starts using `plone.api` in the core of Plone 4.3, it is harder to notice.

**Comment by gforcada** [comment]
I'm in general 👍 on it, I share your concern of plone.api on 4.3 core, but given the amount of fixes that go there, is probably a minor thing...

**Comment by fredvd** [comment]
Closed with https://github.com/plone/buildout.coredev/pull/359
