### ISSUE TITLE
Babel not pinned when running translations for 4.3

### ISSUE THREAD

**Issue by fredvd** [plone/buildout.coredev#361]
I'm trying to run translation updates to do some fixes for Plone 4.3 but they're also missing in 5.0/5.1 . 

When I run bin/buildout -c experimental/i18n.cfg in the 4.3 branch to create the translation scripts, I get a warning that Babel is unpinned and version 2.5 (latest from pypi) is used in all bin/* scripts.  When  I run the same for coredev 5.1 I get no warning and the pinned version 1.3 is used.

@vincentfretin You ran the i18n update scripts at the end of 2016 for the last time for Plone 4.3 Did you notice this, Is it problematic?

I'd like to sync the translations again for Plone 4.3 again to do some translation updates. I see there are others missing, but it started with https://github.com/plone/plone.app.contenttypes/commit/a428777002c208a6dfb6dd0b4be07d31fe9135eb

**Comment by vincentfretin** [comment]
Plone doesn't use babel AFAIK, only i18ndude.

**Comment by jensens** [comment]
Anyway, I think its ok to add the same pin as in 5.1 to 4.3, Babel 2.x is a completely different thing.

**Comment by vincentfretin** [comment]
I see that Babel = 1.3 is in versions.cfg in buildout.coredev 4.3, so closing it.
