### ISSUE TITLE
'Edit on GitHub' button/link is incorrect

### ISSUE THREAD

**Issue by tkimnguyen** [plone/buildout.coredev#379]
On http://buildoutcoredev.readthedocs.io/en/5.2/updateme.html the 'Edit on GitHub' link in the breadcrumbs/header of the page points to https://github.com/plone/buildout.coredev/blob/origin/5.2/docs/updateme.rst but should be https://github.com/plone/buildout.coredev/blob/5.2/docs/updateme.rst (without 'origin').

![screen shot 2017-11-09 at 8 34 32 pm](https://user-images.githubusercontent.com/815418/32642556-b12670dc-c59a-11e7-8ad1-dad9dfcf8ba4.jpg)

The line that generates that URL is https://github.com/plone/plone.themepreview/blob/master/source/_templates/breadcrumbs.html#L10 but I don't see where `github_version` or `conf_py_path` are set... (one of those contains the extraneous 'origin' string)

**Comment by tkimnguyen** [comment]
Related to https://github.com/plone/buildout.coredev/pull/378

**Comment by jensens** [comment]
Is the readthedocs version maintained? Who has access there? I think it is enough to have the docs in docs.plone.org. IMO we should get rid the dup at readthedocs.

**Comment by tkimnguyen** [comment]
Maybe @svx knows?

**Comment by svx** [comment]
@jensens yes that is the idea since a long time, remove it from RTD.

I ask various times already but no one with permissions on the RTD account answered ever :)

**Comment by svx** [comment]
@tkimnguyen This is 'simply' a combination of settings in the conf.py of this Sphinx build and project settings on RTD.

**Comment by jensens** [comment]
@svx, do you know who has access?

**Comment by svx** [comment]
@jensens no sadly not, otherwise it would be already gone from RTD since years :)

**Comment by tkimnguyen** [comment]
Can we ask someone at RTD to do it then? Or tell us who uploaded that?

**Comment by mauritsvanrees** [comment]
The project page at http://readthedocs.org/projects/buildoutcoredev/ shows the owners: @zupo @davisagli @eleddy @claytron.
What do we want to ask them? Remove the entire project, or maybe add a redirect to docs.plone.org if that is possible?

**Comment by zupo** [comment]
I confirm I (still) have admin access. Let me know how I can help.

Ideal scenario: tell me which username should I assign admin permissions to.

**Comment by jensens** [comment]
I think a redirect (if easily possible) is the most user friendly option, otherwise a complete removal is ok too, since there is google et al...

**Comment by zupo** [comment]
I don't see an option of a redirect, but I can assign someone as admin to take a deeper look.

**Comment by balavec** [comment]
As far as I can tell this has been resolved. @tkimnguyen should the issue be closed?

**Comment by mauritsvanrees** [comment]
Seems to be working yes. Closing.
