### ISSUE TITLE
deduplicate Contributor's Agreement info

### ISSUE THREAD

**Issue by tkimnguyen** [plone/buildout.coredev#393]
re: https://github.com/plone/documentation/issues/672 and https://github.com/plone/buildout.coredev/pull/386 

I think the link https://plone.org/foundation/contributors-agreement/agreement.pdf on the page https://docs.plone.org/develop/coredev/docs/contributors_agreement_explained.html should point instead to https://plone.org/foundation/contributors-agreement/ rather than directly to the PDF, and the information here on docs.plone.org about the contributor agreement should not be duplicated here; it is best left on plone.org

**Comment by mrsaicharan1** [comment]
I would like to fix this.

**Comment by mrsaicharan1** [comment]
Could you provide me a link to the repo where I could fix the broken link?

**Comment by mrsaicharan1** [comment]
I've fixed the broken link issue. Could you review this on https://github.com/plone/buildout.coredev/pull/411?
And also, I think it would be better to provide a download link to the contributors' agreement pdf on the page which I've provided the link to.

**Comment by gforcada** [comment]
@mrsaicharan1 the link to the PDF is already there on that page :-)

**Comment by fredvd** [comment]
Fixed, referenced pr's are merged afaics.
