### ISSUE TITLE
Add missing i18n-find-untranslated on 4.3 branch?

### ISSUE THREAD

**Issue by gforcada** [plone/buildout.coredev#425]
I wrote some new jenkins jobs (we already had one but was only tracking latest branch, i.e. 5.2 right now) that check if there are strings not marked for translation on each major branch (4.3, 5.0, 5.1 and 5.2).

It is using the fantastic ``i18n-find-untranslated`` on ``experimental/i18n.cfg``.

It is missing on 4.3 though. Do we want that there as well?

/cc @vincentfretin @plone/release-team

**Comment by mauritsvanrees** [comment]
I suppose that not many people will be focused on translations for 4.3 anymore.
Then again, a language may have been at 100% previously and people may want to keep it that way, so it would help to have a page where you can easily see how well your language is doing currently. There is always the possibility that some more message ids are added or changed.
So if it's not too much trouble: yes, please. 👍
