### ISSUE TITLE
Outdated version pinning on Plone 5.0

### ISSUE THREAD

**Issue by hvelarde** [plone/buildout.coredev#509]
https://dist.plone.org/release/5.0-latest/versions.cfg has outdated versions of both, setuptools and zc.buildout.

it lists:

```ini
setuptools = 26.1.1
zc.buildout = 2.5.3
```

it should be:

```ini
setuptools = 33.1.1
zc.buildout = 2.9.5
```

* https://github.com/plone/buildout.coredev/blob/5.0/versions.cfg#L33-L35
* https://github.com/plone/buildout.coredev/blob/5.0/requirements.txt

**Comment by hvelarde** [comment]
cc @esteele @plone/framework-team

**Comment by gforcada** [comment]
@hvelarde make a pull request with these version bumps (both in requirements.txt as well as versions.cfg please!)

**Comment by hvelarde** [comment]
as you can see in the links above, they are updated; I think we somehow forgot to update the `versions.cfg` file in dist.plone.org and I can't do anything about that.

**Comment by jensens** [comment]
@plone/release-team I think this one is for you

**Comment by gforcada** [comment]
Oops, sorry, i did not read carfeully enough.

**Comment by mauritsvanrees** [comment]
5.0-latest always refers to the latest 5.0 release. Not the latest coredev.

**Comment by hvelarde** [comment]
I see, the problem is buildout is failing using those versions.

**Comment by idgserpro** [comment]
>5.0-latest always refers to the latest 5.0 release. Not the latest coredev.

@mauritsvanrees so, wouldn't it be nice to have one:

```https://dist.plone.org/release/5.0-latest/requirements.txt```

with the corresponding versions of 5.0-latest?

**Comment by vincentfretin** [comment]
This seems fixed, we have
```
setuptools = 33.1.1
zc.buildout = 2.9.5
```
in https://dist.plone.org/release/5.0-latest/requirements.txt
and https://github.com/plone/buildout.coredev/blob/5.0/requirements.txt
