### ISSUE TITLE
PLIP jobs: test against Py3 and Py2

### ISSUE THREAD

**Issue by thet** [plone/buildout.coredev#549]
Currently we only test against Python 2 on PLIP jobs. We probably need a way to test against Python 3 and Python 2.
The easiest way to do this might be to provide 2 buildout configurations per PLIP.

**Comment by gforcada** [comment]
Yeah, as I was fixing the jobs earlier before I did notice that...

Your idea sounds like a good solution. Let me put my kids to sleep and I will try to work on that.

**Comment by thet** [comment]
:D 
but it's no hurry!

**Comment by gforcada** [comment]
@thet done! Now we have PLIP jobs targeting 2.7/3.6/3.7 things might be a bit off still, let me know:

https://github.com/plone/jenkins.plone.org/commit/bac9d0e47f5d2dd293ab66819e3b722a565d90a8

**Comment by thet** [comment]
@gforcada awesome!
I recognized a problem when running:
https://jenkins.plone.org/view/PLIPs/job/plip-plone-staticresources-2.7/1/console

the plip configuration is referenced incorrectly - absolute to the filesystem's root:
```
buildout buildout:git-clone-depth=1 -c /plip-1653-staticresources.cfg
```

**Comment by thet** [comment]
@gforcada reminder for the broken PLIP initialization

**Comment by gforcada** [comment]
@thet I will have a look right now

**Comment by gforcada** [comment]
Fixed (at least that bug, there might be others :sweat_smile: ): https://jenkins.plone.org/view/PLIPs/job/plip-plone-staticresources-2.7/3/console

**Comment by thet** [comment]
@gforcada tnx!
