### ISSUE TITLE
Buildout fails on Mac with Xcode 5.1

### ISSUE THREAD

**Issue by tomgross** [plone/buildout.coredev#55]
Getting distribution for 'watchdog'.
cc1: error: -Werror=unused-command-line-argument-hard-error-in-future: No option -Wunused-command-line-argument-hard-error-in-future
error: Setup script exited with error: command '/usr/bin/gcc-4.2' failed with exit status 1
An error occurred when trying to install watchdog 0.8.2. Look above this message for any errors that were output by easy_install.
While:
  Installing test.
  Getting distribution for 'watchdog'.
Error: Couldn't install: watchdog 0.8.2

See also http://blog.manbolo.com/2014/03/26/xcode-5.1-breaks-python-native-extensions-and-ruby-gems

**Comment by tomgross** [comment]
It is the [reload] entry point of plone.app.robotframework. Uncommenting it works as a workaround.

**Comment by jensens** [comment]
@tomgross what is state here?

**Comment by tomgross** [comment]
I haven't encountered this issue recently. Closing it.
