### ISSUE TITLE
Document usage of new style resources, grunt, etc. 

### ISSUE THREAD

**Issue by tomgross** [plone/buildout.coredev#58]
Document usage of new style resources, grunt, etc. in the core development section:

http://docs.plone.org/develop/plone-coredev/index.html

**Comment by jensens** [comment]
related: plone/Products.CMFPlone#1300

**Comment by jensens** [comment]
i think this is not a coredev buildout thing, this is also covered in the PLIP to the above PR here plone/Products.CMFPlone#1277 - it will be documented!
