### ISSUE TITLE
TinyMCE usability fail after creating new site

### ISSUE THREAD

**Issue by zopyx** [plone/buildout.coredev#59]
Create a new Plone 5 site and edit the front-page.
The default size of the editor window of the editor window is much bigger than the visual error.
In the general the TinyMCE toolbar should be visible at any time when you edit a richtext field. The default size of the editor should limited to the visual area.

**Comment by vangheem** [comment]
Perhaps this ticket should be on mockup or Products.CMFPlone.

**Comment by zopyx** [comment]
I don't know where it should be...how should Plone users that are not developers find the right bug tracker?...big problem...

**Comment by vangheem** [comment]
Yes, it's a big problem. I think it's going to be discussed by the framework team. No one looks at trac and there are too many repos in the plone github group to make any sense out of it.

**Comment by ebrehault** [comment]
As Trac will be soon abandonned, I think the GitHub issues on
Product.CMFPlone repository could be the most logical place.

Eric

**Comment by jensens** [comment]
yes, move to Product.CMFPlone please
