### ISSUE TITLE
trollius partially removed from PyPI

### ISSUE THREAD

**Issue by jamadden** [plone/buildout.coredev#597]
On Python 2.7, Plone 5.2 [installs trollius==2.2](https://github.com/plone/buildout.coredev/blob/3e14b400b4a2e71c53d7b74b4cd41baf4938300a/versions.cfg#L304), and Plone 5.1 [installs trollius==2.1](https://github.com/plone/buildout.coredev/blob/5.1/versions.cfg#L65).

The source distributions (.tar.gz) for both of those releases were recently removed from PyPI. We were able to restore some wheels for both of them, but those do not work on Windows (unfortunately they install just fine, but they fail at runtime with import errors). 

A 2.2.post1 and a 2.1.post2 have been uploaded to address this. They restore the source, and for 2.2 they include binary wheels for Windows. Perhaps the version pins here should be updated? (Disclaimer: I'm not a Plone developer or user.)

See https://github.com/zopefoundation/ZEO/issues/146 for more discussion.

**Comment by mauritsvanrees** [comment]
On https://dist.plone.org/release/5.1.5/ we have trollius-2.1.tar.gz. So people who have that in the find-links of their buildout, can still get it. For 5.2.0 this is not the case.
But anyway, that is not your point.

Seems good to update the pins in both cases yes. Let me try that.

**Comment by mauritsvanrees** [comment]
Done in a2da872e9bd0c81aef1bcaaf7e9426c00994eaa6 for Plone 5.1.
Done in 680779cd467f2bf897659b8e558b01631a54bdda for Plone 5.2.
Note that trollius is not used in Plone 5.0 or earlier.

Thanks for the warning and for fixing the situation on PyPI!
