### ISSUE TITLE
Clean up plips folder?

### ISSUE THREAD

**Issue by gforcada** [plone/buildout.coredev#64]
Just taking a look at https://github.com/plone/buildout.coredev/tree/5.0/plips shows lots of really old plips (5+ years some of them).

Is there any need to keep all of them around?

With the work that we are doing on the new jenkins.plone.org setup, one approach to make it easier for plips to be merged successfully would be to create a jenkins job for each plip. So a jenkins job would be monitoring buildout.coredev and keep creating/deleting jobs as they would be found on the plips folder, hence a clean up on it would be nice to not create lots of garbage jobs.

/cc @tisto

**Comment by vangheem** [comment]
IMO, please clean it up. Should only be for active plips.

**Comment by tisto** [comment]
+1

You can check here which PLIPs are still relevant: https://docs.google.com/spreadsheets/d/15Cut73TS5l_x8djkxNre5k8fd7haGC5OOSGigtL2drQ/edit?authkey=CLH59a8D&hl=en&authkey=CLH59a8D#gid=3

**Comment by gforcada** [comment]
Cool, thanks!
