### ISSUE TITLE
Pin cffi to 1.14.4 in order to avoid build failures on Apple M1

### ISSUE THREAD

**Issue by tisto** [plone/buildout.coredev#711]
cffi is a dependendency of cryptography which is a dependency of PyJWT which is used by plone.restapi.

Plone installations currently fail because cffi 1.14.3 does not work on the new Apple M1 ARM architecture. Pinning to 1.14.4 fixes the problem:

```
# cffi 1.14.3 fails on apple m1
cffi = 1.14.4
```

@mauritsvanrees if it is not too much hassle, maybe we can add this pin to the upcoming 5.2.4 release. This will make Apple M1 users happy and avoid lots of pain that we had to go through to figure things out.

@sneridagh @iFlameing can you confirm that 1.14.4 is the correct version? I just ran into that problem myself this morning. No clue why I didn't had the problem before.

**Comment by tisto** [comment]
@mauritsvanrees one other thing that most likely you already took into account. Cryptography 3.4 requires a RUST complier on the system and this fails on the M1 as well (on other systems as well). So we had to pin cryptography to 3.3.2 on all our systems:

```
# cryptography 3.4 requires a rust compiler installed on the system:
# https://github.com/pyca/cryptography/blob/master/CHANGELOG.rst#34---2021-02-07
cryptography = 3.3.2
```

**Comment by iFlameing** [comment]
@tisto I can confirm that  cffi 1.14.4 is the right version.

**Comment by tisto** [comment]
@mauritsvanrees FYI: I created a PR for this: https://github.com/plone/buildout.coredev/pull/712

**Comment by fredvd** [comment]
Fixed
