### ISSUE TITLE
buildout freezes because of http links

### ISSUE THREAD

**Issue by wesleybl** [plone/buildout.coredev#763]
A colleague of mine had Plone 4.3 buildout frozen because of http links. The buildout extends https://dist.plone.org/release/4.3-latest/versions.cfg and it has http links

http://dist.plone.org/versions/zopetoolkit-1-0-8-zopeapp-versions.cfg
http://dist.plone.org/versions/zope-2-13-30-versions.cfg

When he downloaded the https://dist.plone.org/release/4.3-latest/versions.cfg file and changed the links to https, the buildout worked.

On my machine, with the same versions of setuptools (42.0.2) and buildout (2.13.2), it worked even with http.

What can this be? Is it possible to change the links to https?

**Comment by mauritsvanrees** [comment]
You are automatically redirected from http to https, at least in a browser. Maybe your colleague has some configuration setting to not do this?

But it seems logical to change these `dist.plone.org` files to point to https. I can do this, and would do this in 4.3.20, 5.0.10, and 5.1.7.
Is anyone against?

**Comment by wesleybl** [comment]
> Maybe your colleague has some configuration setting to not do this?

He browser he is redirected and he can access. Not really its what it can be. Perhaps some OS dependencies that Python needs are not installed.

> But it seems logical to change these dist.plone.org files to point to https. I can do this, and would do this in 4.3.20, 5.0.10, and 5.1.7.

It would be great.

**Comment by mauritsvanrees** [comment]
I have updated [4.3.20](https://dist.plone.org/release/4.3.20/versions.cfg) and [5.0.10](https://dist.plone.org/release/5.0.10/versions.cfg).
5.1.7 was already extending https.

**Comment by wesleybl** [comment]
@mauritsvanrees  can you do the same with Plone 4.3.17?

https://dist.plone.org/release/4.3.17/versions.cfg

**Comment by mauritsvanrees** [comment]
Done.

**Comment by wesleybl** [comment]
@mauritsvanrees now I bumped into the url:

https://dist.plone.org/versions/zope-2-13-27-versions.cfg

Can you change it please?

**Comment by mauritsvanrees** [comment]
I have now used sed to replace it in all files on dist.plone.org.

**Comment by wesleybl** [comment]
> I have now used sed to replace it in all files on dist.plone.org.

Great! Thank you!
