### ISSUE TITLE
Python 2.7 got removed from Github Actions / setup-python

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/buildout.coredev#878]
See the [latest 5.2 run](https://github.com/plone/buildout.coredev/actions/runs/5555075316).  It says:

> Version 2.7 with arch x64 not found.
> The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

There is indeed no mention of 2.7 in there.

Ah, going to the job [shows a bit more](https://github.com/plone/buildout.coredev/actions/runs/5555075316/jobs/10145730914#step:4:8):

> Warning: The support for python 2.7 will be removed on June 19. Related issue: https://github.com/actions/setup-python/issues/672

The comments contain some hints we could try, like this:

```
runs-on: ubuntu-20.04
    container:
      image: python:2.7.18-buster
```

I should refrain from trying that today, I am letting myself get too distracted already.

**Comment by gforcada** [comment]
Seems this is fixed already 🎉
