### ISSUE TITLE
Set 6.1 as default branch on GitHub

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/buildout.coredev#907]
Currently 6.0 is the default branch.  We should switch this to 6.1, that is where the action is happening.  I can do that.

(Actually, I went looking how to do this, and had trouble finding it.  But you simply go to Settings, and then in the main text area the second section is called 'Default branch'.)

I am not aware of anything that could go wrong because of this, but thought I would ask just to be sure.  Better safe than sorry.  And it is a good way to announce this tiny change.
Anyone against?

**Comment by davisagli** [comment]
@mauritsvanrees Sounds good to me, since we already have a branch protection rule for the 6.1 branch.

**Comment by mauritsvanrees** [comment]
Done.
